# Generated by Django 5.2.15 on 2026-06-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCPConnectorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Provision/update the OAuth client when this is saved.')),
                ('app_name', models.CharField(blank=True, help_text="Client name shown on the OAuth consent page. Blank uses DJANGO_MCP_KIT['OAUTH_APP_NAME'].", max_length=150)),
                ('redirect_uris', models.TextField(blank=True, help_text='Allowed redirect URIs, one per line.')),
                ('skip_consent', models.BooleanField(default=False, help_text='Auto-approve authorization (skip the consent page).')),
                ('client_id', models.CharField(blank=True, editable=False, max_length=100)),
            ],
            options={
                'verbose_name': 'MCP connector',
            },
        ),
    ]
