# Generated by Django 6.0.6 on 2026-06-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_wagtail_connector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcpconnectorsettings',
            name='client_id',
            field=models.CharField(blank=True, help_text='Generated Client ID — paste this into the connector.', max_length=100),
        ),
    ]
